language: c
sudo: require

matrix:
  include:
  - os: linux
    compiler: gcc
    env: CC=gcc-4.8
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y autotools-dev
      - sudo apt-get install --only-upgrade -y autoconf 
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
  - os: linux
    compiler: gcc
    env: CC=gcc-4.9
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y autotools-dev
      - sudo apt-get install --only-upgrade -y autoconf 
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
  - os: linux
    compiler: gcc
    env: CC=gcc-5
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y autotools-dev
      - sudo apt-get install --only-upgrade -y autoconf 
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - autotools-dev
        - autoconf
  - os: linux
    compiler: gcc
    env: CC=gcc-6
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y autotools-dev
      - sudo apt-get install --only-upgrade -y autoconf 
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - autotools-dev
        - autoconf
  - os: osx
    compiler: clang
    env: CC=clang
    before_install:
      -  brew install autoconf
      -  brew install automake
  
script:
  - autoreconf -i 
  - ./configure  
  - make 
  - make test
