language: c
sudo: false

matrix:
  include:
  - os: linux
    compiler: gcc
    env: CC_OQS=gcc-4.8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - autotools-dev
        - autoconf
  - os: linux
    compiler: gcc
    env: CC_OQS=gcc-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.9
        - autotools-dev
        - autoconf
  - os: linux
    compiler: gcc
    env: CC_OQS=gcc-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - autotools-dev
        - autoconf
  - os: linux
    compiler: gcc
    env: CC_OQS=gcc-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - autotools-dev
        - autoconf
  - os: osx
    compiler: clang
    env: CC_OQS=clang
    before_install:
      -  brew install autoconf
      -  brew install automake
  
script:
  - autoreconf -i 
  - ./configure  
  - make 
  - make test
